#!/usr/bin/env bash
#
# Takes an Arabic number and outputs the Chinese equivalent.
# This is used to make Tmux's window indices display as Chinese numbers.

default_indices="〇|一|二|三|四|五|六|七|八|九|十|十一|十二|十三|十四|十五|十六|十七|十八|十九|二十"
window_indices=$(tmux show-option -gqv "@window_indices")
if [ -z "$window_indices" ]; then
  window_indices=$default_indices
fi;

IFS='|' read -r -a array <<< "$window_indices"
echo "${array[$1]}"
